#!/bin/bash

# Unmaintained repo msg
echo "This repository is no longer being maintained, use: https://raw.githubusercontent.com/ishare2-org/ishare2-cli/main/ishare2 instead"

# Pause for 3 seconds
sleep 3

# Download and execute the ishare2 script
curl -fsSL https://raw.githubusercontent.com/ishare2-org/ishare2-cli/main/ishare2 -o /usr/sbin/ishare2 && chmod +x /usr/sbin/ishare2
exit 0
